### ISSUE TITLE
Something is not quite right with using runspaces

### ISSUE THREAD

**Issue by nightroman** [PowerShell/Polaris#102]
As far as I understand, the runspace pool is supposed to be used during the loop.
Thus, runspaces should be used by PowerShell instances from the connected pool.
But in fact, the code creates and opens a new runspace for each PowerShell instance:

https://github.com/PowerShell/Polaris/blob/15a7061024ce057efe854dab085b978a52a5d879/lib/Polaris.Class.ps1#L165-L166

**Comment by Tiberriver256** [comment]
Good eye. Thanks @nightroman!

**Comment by Tiberriver256** [comment]
I was just going to do a quick patch but I think it might be a bit of work to make sure the $synchash is being passed effectively. Not too bad and I've got an idea on how it should work but I'm going to hold off pending Issue #93 and #104 as we may be replacing all of the runspaces entirely.

Feel free to jump in and look at the code on either of those and throw out any feedback.

**Comment by nightroman** [comment]
I did not follow the recent development closely. If workspaces are not used anymore, should we close this?

**Comment by tylerl0706** [comment]
We can! 🎉
