### ISSUE TITLE
SendHTML Question

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/Polaris#108]
Hi Guys, 

I have a short question concerning, concerning how to use Polaris to send already generated HTML. Abviously, I am doing something wrong, but I can't figure out what.

This is my example code:

```powershell

New-PolarisRoute -Path /sendhtml -Method GET -ScriptBlock {
    $file= "C:\MyHtml\HTML_Example.html"  
    $htmlContent = gc $file
    $reponse.sendhtml($htmlContent)

}

$app = Start-Polaris -Port 8082 -MinRunspaces 1 -MaxRunspaces 5 -UseJsonBodyParserMiddleware -Verbose # all params are optional

#Didnt work

```

When I open my browser, and navigate to http://localhost:8082/sendhtml It take quite some while, but after some 20 seconds, it sends me a file called 'sendhtml', which is not the content that I had in my html_Example.

I tried the following different ways to try to send html back, all without success:

```powershell

New-PolarisRoute -Path /send -Method GET -ScriptBlock {
    $file= "C:\MyHtml\HTML_Example.html"  
    $htmlContent = gc $file
    $reponse.send$htmlContent)

}

$app = Start-Polaris -Port 8082 -MinRunspaces 1 -MaxRunspaces 5 -UseJsonBodyParserMiddleware -Verbose # all params are optional

#Didnt work as well

```

```powershell

$myhtmlScript = "C:\Scripts\example01.ps1" #this script generates HTML on the fly
$htmlcontent = gc $myhtmlScript
$content = [scriptblock]::Create($htmlcontent) #gc $myhtmlScript

New-polarisRoute -Path /sb -method GET -ScriptBlock $content #did not work
New-PolarisRoute -Path /pshtml -Method GET -ScriptPath $myhtmlScript #did not work

$app = Start-Polaris -Port 8082 -MinRunspaces 1 -MaxRunspaces 5 -UseJsonBodyParserMiddleware -Verbose # all params are optional

```

## error behaviour

The error behaviour is 'the same' for all the routes above: It takes some time to load (20 sec or so) and sends me a file with the name of the route back, which seems to be empty ($null).

Can you tell me what I am doing wrong, or is this perhaps not supported yet?

Thanks

**Comment by tylerl0706** [comment]
Thanks for the details! Con you be a bit more specific about what you get back?

Screenshots or exact text would be ideal

**Comment by tylerl0706** [comment]
Did you try `Get Content` with` -Raw`?

**Comment by Stephanevg** [comment]
hmmm, well difficult to give more details, but i'll try:

There is actually nothing happening. Like i said, I ask for the route in let's say google Chrome, where is specifiy for example the following route in my browser.

```powershell
http://localhost:8082/sendhtml
```

It then takes a few second (10 to 20 second) and then, send me a file back (nothing on the screen in the broswer, it is simply a blank screen).  (I am not gonna take a screen shot of a white screen..)

That file that is sent back, has each time the name of the route I querying (in this example 'sendhtml').


This is the file that is sent back looks like this on the file system:

![image](https://user-images.githubusercontent.com/6302961/38824251-f1457db8-41a8-11e8-97c4-f276d739773e.png)

And this is it's content:

![image](https://user-images.githubusercontent.com/6302961/38824266-ff7360a8-41a8-11e8-94a3-aa6e48089c7f.png)

No I haven't tried with RAW but I'll give it a shot when I have a minute.
BUT, I have the same behaviour with:

```powershell

New-PolarisRoute -Path /pshtml -Method GET -ScriptPath "C:\Scripts\example01.ps1" #did not work

```
Is there a way for me to debug this in some way or another?
must the file have a specefic encoding? (using the default one from Vscode).
Should the files be located in a specefic folder to be able to be read by polaris perhpas?

**Comment by Stephanevg** [comment]
I tried the following as well:

```powershell
 $htmlContent = gc $RawHTMLFile -Raw
    New-polarisRoute -Path /p -method GET -ScriptBlock {
           $response.sendhtml("<p>Woop p</p>")
        }
```
I do have the exact same issue (empty file called 'p'  that is getting download ).

When I use this:
```powershell
 $htmlContent = gc $RawHTMLFile -Raw
    New-polarisRoute -Path /p -method GET -ScriptBlock {
           $response.send("<p>Woop p</p>")
        }
```

Then I have the following display:
![image](https://user-images.githubusercontent.com/6302961/38834452-d33ac290-41c8-11e8-96e3-01971ce48d25.png)

**Comment by Tiberriver256** [comment]
Hi @Stephanevg,
There currently is not a method on the $response object called sendhtml. Where did you see an example using that method?

Your last attempt is almost correct. If you are sending html to the browser you will need to set the content type before sending. 

See the wiki here for more details:
https://github.com/PowerShell/Polaris/wiki/$response.SetContentType

The following should work:

```ps
 $htmlContent = gc $RawHTMLFile -Raw
    New-polarisRoute -Path /p -method GET -ScriptBlock {
           $response.SetContentType("text/html");
           $response.send("<p>Woop p</p>")
        }
```

**Comment by tylerl0706** [comment]
slight edit to @Tiberriver256's example that uses the `$htmlContent` 🙂 
```
 $htmlContent = gc $RawHTMLFile -Raw
    New-polarisRoute -Path /p -method GET -ScriptBlock {
           $response.SetContentType("text/html");
           $response.send($htmlContent)
        }
```

**Comment by Stephanevg** [comment]
@Tiberriver256 Yeah, sorry for that, it actually appeared in my 'intelisense' on VSCode, don't know why.

Indeed, @tylerl0706 Adding the ContentType fix the issue I had with ScriptBlock.

How would I set the content type when I call a script using ``` Scriptpath``` ?

In the following example, example01.ps1 generates HTML that I would like to send back.

```powershell
New-PolarisRoute -Path /pshtml -Method GET -ScriptPath "C:\Scripts\example01.ps1"
```

How would I handle that? 

thanks!

**Comment by Stephanevg** [comment]
I tried like this, which seem to fail in the same way as I described above (File beeing downloaded with the name of the route

```powershell
New-PolarisRoute -Path /woop -Method get -ScriptBlock {
    $RawHTMLFile = gc "C:\Examples\Example.html" 
    $response.SetContentType("text/html");  
    $response.send($RawHTMLFile);  
           
} -Force

```
and calling polaris either like this:

```powershell
# Start the server
$app = Start-Polaris -Port 8085 -MinRunspaces 1 -MaxRunspaces 5 -Verbose # all params are optional
```

or like this:

```powershell
$app = Start-Polaris -Port 8084 -MinRunspaces 1 -MaxRunspaces 5 -UseJsonBodyParserMiddleware -Verbose

```

**Comment by tylerl0706** [comment]
@Stephanevg your questions answered:

----

> How would I set the content type when I call a script using Scriptpath ?

you can set it in the script like this, just as you would in the script block:

example01.ps1:

```powershell
$htmlContent = Get-Content foo.html -Raw
$response.SetContentType("text/html")
$response.send($htmlContent)
```

and then this will work:

```powershell
New-PolarisRoute -Path /pshtml -Method GET -ScriptPath "C:\Scripts\example01.ps1"
```

This is because PowerShell script files are really just script blocks in a file 🙂 

----

> I tried like this, which seem to fail in the same way as I described above (File beeing downloaded with the name of the route

In your script block you didn't add the `-Raw` like I mentioned above.

You have:

```powershell
New-PolarisRoute -Path /woop -Method get -ScriptBlock {

    $RawHTMLFile = gc "C:\Examples\Example.html" 

    $response.SetContentType("text/html");  
    $response.send($RawHTMLFile);  
           
} -Force
```

you need:

```powershell
New-PolarisRoute -Path /woop -Method get -ScriptBlock {

    # You need the `-Raw` here
    $RawHTMLFile = gc "C:\Examples\Example.html" -Raw

    $response.SetContentType("text/html");  
    $response.send($RawHTMLFile);  
           
} -Force
```

----

Let me know if that works for you!

**Comment by Stephanevg** [comment]
Hi @tyler Thanks

```powershell

New-PolarisRoute -Path /html -Method get -ScriptBlock {
   
$html = @"
<!DOCTYPE html>
<html>

<head>
<title>woop title</title>
<link href=css/normalize.css rel=stylesheet>

</head>

<Body>
<header>
    <img height="100" width="400" src=https://i0.wp.com/powershelldistrict.com/wp-content/uploads/2016/01/logo_pd_quadri.png alt="logo powershell">
    <h1>
        This is h1 Title in header
    </h1>
    <div>
        <p>
            This is simply a paragraph in a div.
        </p>
    </div>
</header>
<p>
    <h1>
        This is h1
    </h1>
    <h2>
        This is h2
    </h2>
    <h3>
        This is h3
    </h3>
    <h4>
        This is h4
    </h4>
    <h5>
        This is h5
    </h5>
    <h6>
        This is h6
    </h6>
    <strong>plop</strong> Woop
</p>
<p>
    <table>
        <caption>
            This is a table generated with PSHTML
        </caption>
        <thead>
            <tr>
                <th>number1</th>
                <th>number2</th>
                <th>number3</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Child 1.1</td>
                <td>Child 1.2</td>
                <td>Child 1.3</td>
            </tr>
            <tr>
                <td>Child 2.1</td>
                <td>Child 2.2</td>
                <td>Child 2.3</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td>Table footer</td>
            </tr>
        </tfoot>
    </Table>
</p>
<p>
    <a href="http://powershellDistrict.com">
This links point to PowershellDistrict
</a>
</p>
<footer>
    <h6>
        This is h1 Title in Footer
    </h6>
</footer>
</Body>

</html>
"@

    $response.SetContentType("text/html");  
    $response.send($html);  
           
} -Force
```

My call via IE / chrome looks like this:

```powershell
$app = Start-Polaris -Port 8086 -MinRunspaces 1 -MaxRunspaces 5 -UseJsonBodyParserMiddleware -Verbose # all params are optional

```

In the powershell ISE where I started the app, I see the following poppung up:



```powershell
Parsed Route: html

Request Method: GET

```

The example seems so basic to me, and I don't get what I am doing wrong.

I also tried using the -RAW (before simply copying and pasting the complete html content in the scriptblock as in my code above) but I have the same results: It seems that nothing is sent back.

I tried to put some break points on the functions, but they are unfortunatley not hit.

I do have the following two questions:
1) what am I doing wrong? (Or is this a bug?) 
2) How can I debug polaris (Set a break point, and have a look into the varaibles content?)

Thanks!

**Comment by Stephanevg** [comment]
OK, I found the issue my self, wrote the fix, and the corresponding pester test that goes along with it.
Basically, it was a really small thingy actually:

### wrong code

```powershell
New-PolarisRoute -Path /html -Method get -ScriptBlock 
```

### Good code:

```powershell
New-PolarisRoute -Path /html -Method GET -ScriptBlock 
```

Did you see it? yep, lower / upper case method.

I have added a fix here --> https://github.com/PowerShell/Polaris/pull/110 and it contains pester tests in it.

Please let me know if I need to change something.

Stéphane

**Comment by tylerl0706** [comment]
Thank you so much for doing that @Stephanevg! 👍

**Comment by Tiberriver256** [comment]
You’re the man!
