### ISSUE TITLE
Pass variables to routes

### ISSUE THREAD

**Issue by Hvid** [PowerShell/Polaris#112]
I would like to be able to pass variables into my routes, but this isn't trivial as they separate runspaces.

Any suggestions on how this could be achieved? I tried to use a .GetNewClosure() on the scriptblock, but this doesn't seem to work across runspaces either.

**Comment by tylerl0706** [comment]
Not 100% sure what you mean but I have 2 answers:

We're working on the scoping issue in this PR #104. This will allow you to define variables outside of your route and use them in your route:
```powershell
$foo = 4
New-PolarisRoute -Method GET -Scriptblock {
  Write-Host $foo
}
```

If you mean pass variables into the route as it executes, I think what you may want is to use Query parameters or the http body of the request the comes in:

Query params:
https://github.com/PowerShell/Polaris/wiki/$request.Query

Body example:
```powershell
New-PolarisRoute -Method GET -Scriptblock {
  $Request.BodyString
  # or if you used the JSON parser there's an object here:
  $Request.Body
}
```

**Comment by Hvid** [comment]
Hi Tyler,

Sorry for being unclear. I'm talking about the scoping issue - Looking forward to PR #104 getting merged. Thanks :)
