### ISSUE TITLE
Setting WWW-Authenticate header property on response object

### ISSUE THREAD

**Issue by sgnewman** [PowerShell/Polaris#115]
I've had issues getting the web page to prompt for basic credentials if none are supplied due the lack of access to the HttpListenerResponse object.  

Unfortunately, you can't set the ['WWW-Authenticate', 'Basic'] header of the response object via the Set-Header that currently exists in the PolarisResponse class.  It just errors with ""The 'WWW-Authenticate' header must be modified using the appropriate property or method.".  I think this is settable directly via the HttpListenerResponse.AppendHeader method...but no way to get at it from what I see, as it's not stored as a rawresponse as is done with the Request object.

Maybe store the rawresponse in the PolarisResponse object like what is currently done in the Request object would fill this gap?

**Comment by tylerl0706** [comment]
Thanks for this! Yeah I think that's a good idea. That way more complex scenarios have access to everything.

**Comment by Tiberriver256** [comment]
Agreed, we @Hvid did the same thing for request here if you want to check out the code and submit a PR @sgnewman otherwise Tyler or I will probably get to it pretty quick.

https://github.com/PowerShell/Polaris/pull/105/files

**Comment by sgnewman** [comment]
Yeah, I saw that and assumed there was a reason it wasn't duplicated for the response...

I'll take a crack at it when I get home; apparently non-enterprise github is blocked for me here...jerks.

**Comment by Tiberriver256** [comment]
Merged the changes in for this @sgnewman should be available in the next push to PowerShell gallery. Thanks for putting it in!
