### ISSUE TITLE
Query String Support?

### ISSUE THREAD

**Issue by DigitalDrifta** [PowerShell/Polaris#116]
Hi @tylerl0706 and @Tiberriver256 

_**Firstly thanks for the great work done thus far! I really appreciate it and I'm loving Polaris!**_

I'm trying to find a way to get Polaris to accept a key-value paid in the form of a query string. 
I tried **?environment=dev** in bold but the URL parser seems to chop off everything from the ? onwards.

`New-PolarisGetRoute -Path "/api/v1/workspace?environment=dev" -ScriptBlock {`

**This is the server response:**

```
PS C:\WINDOWS\system32>
request came in: GET /api/v1/workspace?environment=dev

Parsed Route: /api/v1/workspace

Request Method: GET
```

**This is the client response:**

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> Invoke-RestMethod http://localhost/api/v1/workspace?environment=dev
Invoke-RestMethod : Not found
At line:1 char:1
+ Invoke-RestMethod http://localhost/api/v1/workspace?environment=dev
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

Any ideas? I really need to get the query sting working. 

Thanks!

**Comment by sgnewman** [comment]
Think you’re doing it wrong.  It should be:

> New-PolarisGetRoute -Path "/api/v1/workspace" -ScriptBlock {
> 

   $environment = $Request.Query[‘Environment’]
   If($environment -eq ‘dev’){
	….what have you...
   }


 
Scott Newman | Señor Database Administrator
scott.newman@sap.com 
Bellevue WA, 98004

**Comment by Tiberriver256** [comment]
@sgnewman is correct. I apologize for the lack of good examples in the documentation but here is an example of how it should work from our test cases.

**Setting up the route**
---
```ps
# Hello World passing in the Path, Method & Scriptblock
New-PolarisRoute -Path /hellome -Method GET -Scriptblock {
    if ($Request.Query['name']) {
        $Response.Send('Hello ' + $Request.Query['name'])
    }
    else {
        $Response.Send('Hello World')
    }
}
```

**Using the route from PowerShell**
---
```ps
$Result = Invoke-WebRequest -Uri "http://localhost:$Port/hellome?name=PowerShell" -UseBasicParsing
 $Result.Content | Should Be 'Hello PowerShell'
```

Does this solve your question?

**Comment by tylerl0706** [comment]
@Tiberriver256 I feel like we should just have docs in a docs folder rather than using the wiki tab.

**Comment by DigitalDrifta** [comment]
Thanks guys, this works as expected! Fantastic.

2 issues I did pick up though:

1. All the wiki entries reference the old cmdlets (guessing) **New-WebRoute** instead of **New-PolarisRoute**. Not sure if this has been done on purpose or just has not been updated?

2. Invoke-RestMethod returns a valid result even if the URL doesn't match the match the -Path. 
For example If you use the code on https://github.com/PowerShell/Polaris/wiki/$request.Query then run the following command, you still get a valid result:
`Invoke-RestMethod -Uri http://localhost:8082/hellome_THIS_SHOULD_NOT_WORK_SHOULD_IT?name=PowerShell
Hello Powershell`

Is this expected behavior or a bug?

Thanks for the help!

**Comment by tylerl0706** [comment]
1. The wiki is horribly out of date - that's my bad. I'll do an overhaul of those soon (traveling at the moment 🙂)

2. If you wanted to submit a PR to fix that, that would be awesome! Seems pretty straightforward 😀

**Comment by Tiberriver256** [comment]
Did we solve this one for you @DigitalDrifta? At least the original question on query strings anway?

@tylerl0706 has also provided some updated documentation in #122. They are now in the /docs folder for your reference.

**Comment by DigitalDrifta** [comment]
Yeah thanks @Tiberriver256 , my issue has been resolved 👍 For now I'll wait leave my change in place until the agreed upon solution is implemented. 

Sorry for all the hassle, feel like I've kicked a hornet's nest 😆

**Comment by Tiberriver256** [comment]
No hornets nest. Just people who care about making Polaris awesome, which is a good thing. 

Let us know if you find anything else!

**Comment by tylerl0706** [comment]
I think we need to document the Polaris request and Response classes. I wonder if Platyps can understand classes 🤔

**Comment by Tiberriver256** [comment]
I think help for classes needs to be prioritized a bit higher :) 

https://github.com/PowerShell/PowerShell/issues/2225
