### ISSUE TITLE
Discussion: Best practices for managing dependencies

### ISSUE THREAD

**Issue by Tiberriver256** [PowerShell/Polaris#117]
PowerShell does not currently have a great method for managing module specific dependencies. You can specify a module is required but it's on the user to go and install that module. It is the default behavior in PowerShell for modules to be installed globally and this, I think, is considered a good practice for scripting purposes.

Package managers that are more geared towards web development projects like the NuGet CLI and NPM default to installing packages locally to the project as your projects typically have a several dependencies that may conflict with the dependencies of other development projects which are installed on the same server.

I wanted to open this to discuss what we would recommend to people using Polaris. If they want to include dependencies on other PowerShell modules into their Polaris web project, do we extend the default PowerShell package management module to suit our purposes? Do we recommend that they rig up some install scripts themselves with ```install-package -path ./polaris_modules```?

Just really want to kick around some ideas. Any are welcome!

**Comment by tylerl0706** [comment]
So, I thought RequiredModules installed all Gallery dependencies when you do Install-module?

**Comment by tylerl0706** [comment]
(I'm sorry I haven't put it on the Gallery yet 😥 I will, soon, I promise)

**Comment by Tiberriver256** [comment]
Looks like that would be the best practice I was searching for, lol. Looks like WMF 5 brought all the goodness in, somehow I missed all that.

For reference:
https://docs.microsoft.com/en-us/powershell/wmf/5.0/psget_moduledependency
