### ISSUE TITLE
Investigate the use of ASP.NET Routing

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/Polaris#13]
ASP.NET has a middleware package that's used for [routing requests to application logic](https://github.com/aspnet/Routing/).

It likely supports things like query params and route params that Polaris needs to have. We should see how easy it is to add this middleware to Polaris.

**Comment by chriskuech** [comment]
Please comment https://github.com/PowerShell/Polaris/issues/12#issuecomment-347030912 on why I believe we should adhere to .NET Standard.

**Comment by Tiberriver256** [comment]
I think we can close this out correct?

**Comment by TylerLeonhardt** [comment]
Yeah :)
