### ISSUE TITLE
Setup AppVayor and TravisCI to build and run Pester tests

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/Polaris#14]
For a good CI pipeline.

**Comment by tylerl0706** [comment]
I added Travis - the only problem is that Pester on Linux in Travis is a [known issue] (https://github.com/pester/Pester/issues/639). However, once that's fixed, it should be a matter of uncommenting that code.

**Comment by it-praktyk** [comment]
Please try to use the branch [Dev4-1_PSCore_compatibility](https://github.com/pester/Pester/tree/Dev4-1_PSCore_compatibility).

Please report any issues related to Pester on PSCore in the thread mentioned above.

**Comment by tylerl0706** [comment]
@it-praktyk : do you have a recommendation on how to use Pester from that branch in Travis?

**Comment by tylerl0706** [comment]
The issue mentioned above is actually a PowerShell Core issue it seems: https://github.com/PowerShell/PowerShell/issues/5205

I have a build on AppVeyor that's working with .NET Framework 4.5.1 so at the very least, tests are being run against that.

**Comment by tylerl0706** [comment]
Tests are working in Travis now so I re-enabled the tests for Travis!

**Comment by it-praktyk** [comment]
Support for PowerShell Core was merged into the master branch. The new release of Pester based on that is coming.
