### ISSUE TITLE
Maintaining line endings across OS and Editors sucks the joy out of development

### ISSUE THREAD

**Issue by Tiberriver256** [PowerShell/Polaris#148]
We've got a couple of PRs out here to address this but wanted to throw up a quick issue to briefly describe what we're trying to achieve and provide a link between the two PRs.

Depending on your operating system and editor Git or your editor might choose to end all of your lines with either a carriage return and a line feed (CRLF) or just a line feed (LF). Which no one really cares about and it's hard to spot the difference until you start a pull request. If the line endings on a file have been changed from CRLF to LF or vice versa the resulting git diff will show that you have modified every line in the file instead of just highlighting the period you maybe added to the end of a Write-Host statement.

We are wanting to add a few things to our shared development environment to hopefully make us all forget that this was ever even a struggle.

Thanks @jeremymcgee73 for getting this started! 😎😎😎

**Comment by tylerl0706** [comment]
lol at the title. Thanks for opening this.
