### ISSUE TITLE
When serving a static folder, there is no response for folders

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/Polaris#16]
Consider the example:

```powershell
New-StaticRoute -FolderPath "./static" -RoutePath "/public"
```
`./static` contains:
`index.html`
`image/`

and `./static/image/` contains:
`hello.png`

we can make requests to:
`/public/index.html`
`/public/image/hello.png`
just fine... 
but `/public/image` hangs.

This is because Polaris can't handle navigating to directories yet. Polaris should support this at the very least by returning the list of things in that directory... ideally links that navigate to that item.

**Comment by kidchenko** [comment]
Hi, I think that this can be a good start point for a new contributor. What do you think? Looks that this feature is not complicated. Can I start working on that?

**Comment by tylerl0706** [comment]
Absolutely, @kidchenko! Pull requests always welcome 😊

**Comment by tylerl0706** [comment]
@Tiberriver256 added this 😀
