### ISSUE TITLE
Consider removing ScriptsToProcess from manifest

### ISSUE THREAD

**Issue by bgelens** [PowerShell/Polaris#168]
# Polaris Bug Report

The use of ScriptsToProcess pollutes the imported modules and doesn't allow for clean removal by typing ```rmo polaris```

## Description of the bug

![image](https://user-images.githubusercontent.com/10071039/49666904-b32e7600-fa59-11e8-91e4-c2455d455828.png)

To remove everything imported I have to ```rmo polaris*``` as well as ```rmo MimeTypes.Class``` and ```rmo New-ScriptblockCallback```

When ScriptsToProcess is removed, the module seems to function fine and only Polaris module is imported.

![image](https://user-images.githubusercontent.com/10071039/49667013-06082d80-fa5a-11e8-90b0-acc2f46747de.png)

![image](https://user-images.githubusercontent.com/10071039/49667028-17e9d080-fa5a-11e8-8e9b-b79eab34cd20.png)

![image](https://user-images.githubusercontent.com/10071039/49667082-4798d880-fa5a-11e8-8a28-3eb2fa03272a.png)

## Expected behavior

Have only one module imported and allow it to be removed in one go as well.

## Version Information

---

Run the following script and copy and paste the results here:

<table>
<colgroup><col/><col/></colgroup>
<tr><th>Name</th><th>Version</th></tr>
<tr><td>Polaris</td><td>0.2.0</td></tr>
</table>
<table>
<colgroup><col/><col/><col/><col/><col/><col/><col/><col/><col/></colgroup>
<tr><th>Platform</th><th>SerializationVersion</th><th>PSEdition</th><th>OS</th><th>PSCompatibleVersions</th><th>PSRemotingProtocolVersion</th><th>PSVersion</th><th>WSManStackVersion</th><th>GitCommitId</th></tr>
<tr><td>Win32NT</td><td>1.1.0.1</td><td>Core</td><td>Microsoft Windows 10.0.18290 </td><td>1.0.-1.-1,  2.0.-1.-1,  3.0.-1.-1,  4.0.-1.-1,  5.0.-1.-1,  5.1.10032.0,  6.1.1.-1</td><td>2.3</td><td>6.1.1</td><td>3.0</td><td>6.1.1</td></tr>
</table>

**Comment by jeremymcgee73** [comment]
I believe this is done so that the types are exported. Can you try running `(Start-Polaris).GetType()` with and without the ScriptsToProcess?

**Comment by bgelens** [comment]
Works ok for me

![image](https://user-images.githubusercontent.com/10071039/49674310-d8c77980-fa71-11e8-8c7a-b52c8be63d1d.png)
