### ISSUE TITLE
GetClientCertificate support?

### ISSUE THREAD

**Issue by bgelens** [PowerShell/Polaris#176]
# Polaris Feature Request

## Is your feature request related to a problem? Please describe

It would be good to be able to call into HttpListenerRequest.[GetClientCertificate](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistenerrequest.getclientcertificate?view=netframework-4.7.2) where Polaris would require client provided certificate. Is this already possible?

## Describe the solution you'd like

I'd like to receive the client provided certificate and be able to handle it as I please. E.g. validate known thumbprint, verify signer, etc.

**Comment by Tiberriver256** [comment]
Hey @bgelens,

The full HttpListenerRequest object is available via:

```pwsh
$Request.RawRequest
```

Looks like `$Request.RawRequest.GetClientCertificate()` is a method but I'm not sure exactly how it would be used. Does that help you?

**Comment by bgelens** [comment]
Hey @Tiberriver256. Thanks for your response. I'm also not sure how to use it so I figured the rawresponse was not usable with this method within Polaris. However I just tried it with plain httplistener and got the same result (which is nothing :) ).

I'll close the issue and investigate some more
