### ISSUE TITLE
Polaris http requests hang when retrieved from client

### ISSUE THREAD

**Issue by suglasp** [PowerShell/Polaris#177]
# Polaris Bug Report

## Description of the bug
Running Powershell Core 6.1.1 on CentOS Linux ("CentOS Linux release 7.6.1810 (Core)")
Installed powershell core from ms repo and did a Install-Module Polaris.
Eventually after running into problems, started off to Install-Module -Scope CurrentUser Polaris for debugging and troubleshooting.
Tested same problem with v0.1.0 and 0.2.0 module versions.

---

## Steps to reproduce
SSH Session #1:
Import-Module Polaris
New-PolarisGetRoute -Path '/helloworld' -Scriptblock { $Response.Send("Hi"); return }
Stop-Polaris; Start-Polaris -Port 8080

SSH Session #2:
Invoke-RestMethod -Method GET -Uri http://machine:8080/helloworld -Verbose
VERBOSE: GET http://machine:8080/helloworld with 0-byte payload
--> // hangs here

SSH Session #1:
had to stop-polaris. Got no response at all in Browser or in session #2

So went troubleshooting. Seems in first place the $Polaris.Log() statements are blocking the I/O.
SSH Session #1:
$env:PSModulePath
/username/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/6/Modules
cd /usr/local/share/powershell/Modules/Polaris/0.2.0/lib
edited file Polaris.Class.ps1 and commented all line statements with "$Polaris.Log(" ...

Stop-Palaris
Remove-Module Polaris
Remove-Module Polaris.Class
Import-Module Polaris
New-PolarisGetRoute -Path '/helloworld' -Scriptblock { $Response.Send("Hi"); return } -Force
Start-Polaris -Port 8080

SSH Session #2:
Invoke-RestMethod -Method GET -Uri http://machine:8080/helloworld -Verbose
VERBOSE: GET http://machine:8080/helloworld with 0-byte payload
--> // hangs here (again)

Now, when i go to session #2 and do Stop-Polaris or Ctrl+C then it gives response in session #2:
VERBOSE: received 2-byte response of content type text/plain
VERBOSE: Content encoding: iso-8859-1

## Expected behavior
Return me a value instant

## Version Information
tested behaviour with Polaris v0.1.0 and v0.2.0

---

<table>
<colgroup><col/><col/></colgroup>
<tr><th>Name</th><th>Version</th></tr>
<tr><td>Polaris</td><td>0.2.0</td></tr>
</table>
<table>
<colgroup><col/><col/><col/><col/><col/><col/><col/><col/><col/></colgroup>
<tr><th>WSManStackVersion</th><th>PSVersion</th><th>PSEdition</th><th>PSCompatibleVersions</th><th>Platform</th><th>GitCommitId</th><th>OS</th><th>PSRemotingProtocolVersion</th><th>SerializationVersion</th></tr>
<tr><td>3.0</td><td>6.1.1</td><td>Core</td><td>1.0.-1.-1,  2.0.-1.-1,  3.0.-1.-1,  4.0.-1.-1,  5.0.-1.-1,  5.1.10032.0,  6.1.1.-1</td><td>Unix</td><td>6.1.1</td><td>Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018</td><td>2.3</td><td>1.1.0.1</td></tr>
</table>

**Comment by Tiberriver256** [comment]
Hi suglasp,

Sounds very similar to a known issue we have on Unix based platforms (OSX / Linux) detailed more in #136, could you try the following before running Polaris and see if the issue clears up for you:

```pwsh
Remove-Module PSReadline
```

(Not meant as a fix, just wanting to narrow the issue down)

Thanks for the detailed bug report!

**Comment by suglasp** [comment]
Works if i do this.

I noticed before (because i came across the 136 issue), i have to do the Invoke-RestMethod in a second ssh tty or it hangs if i try to run it from the same tty where i execute the Start-Polaris CmdLet.

**Comment by thehatchcloud** [comment]
I am also experiencing this isssue - removing PSReadline also resolves the issue for me. Thanks for the workaround @Tiberriver256

**Comment by Tiberriver256** [comment]
Closing as we are tracking this issue in #136
