### ISSUE TITLE
Missing About_routing documentation

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/Polaris#179]
Hi guys,

I was reading through your documentation in the [About_GettingStarted](https://github.com/PowerShell/Polaris/blob/master/docs/about_GettingStarted.md)

I noticed a link was failing.
```
See about_Routing for more details on advanced routing
```

I wanted to fix the link my self and do a PR, but I actually couldn't find an `About_Routing.md` anyware. 
I looked through the repo, but I couldn't find it. Perhaps I miss looked?

**Comment by TylerLeonhardt** [comment]
Hmm that might have been missed! @Tiberriver256 did you ever get a chance to start that `About_Routing.md`?

I just noticed your [unchecked checkbox](https://github.com/PowerShell/Polaris/pull/164) lol

**Comment by Tiberriver256** [comment]
Yep, it's coming in #173 with the full implementation of the router.
