### ISSUE TITLE
thread blocking on Linux (Ubuntu 18)

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/Polaris#184]
# Polaris Bug Report

## Description of the bug

---
Came across a weird thread blocking bug when running Polaris on Ubuntu

## Steps to reproduce

1.  Open pwsh in terminal
2. Start-Polaris -port 8888; New-PolarisRoute -path "/route" -ScriptBlock {$Response.Send("test")}
3.  Go to http://localhost:8888/route (either browser or Invoke-WebRequest)
4. Page hangs
5. Then if you go back to terminal and hit enter, page loads immediately

**Comment by Tiberriver256** [comment]
Hey @mikeTWC1984 - Looks like this is a duplicate of #136.

To confirm could you test with `Remove-Module PSReadLine` and see if the issue goes away? If so, I will close this out to keep the discussion in #136.

**Comment by mikeTWC1984** [comment]
It fixed the problem, thanks!
