### ISSUE TITLE
Documentation: $Request / $Response

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/Polaris#186]
Hi guys,

I noticed that $Request / $Response is not documented (or at least, not here -> https://powershell.github.io/Polaris/)

It would be great to have some use cases on how and when these ones should be used. 
currently, I got this information only because I read it a blog post. 

Cheers

**Comment by Tiberriver256** [comment]
Hey @Stephanevg - I started on some docs and opened a PR as WIP to hopefully get some feedback from you on what would be most useful to see. I started off with just naming properties / methods and a brief description. Let me know what else would be good.
