### ISSUE TITLE
Documentation: Update examples in documentation.

### ISSUE THREAD

**Issue by bateskevin** [PowerShell/Polaris#188]
# Polaris Bug Report

## Description of the bug

I realized that in the docs for New-PolarisStaticRoute the examples don't seem to work, cause the parameter 'Path' does not exist anymore. I don't know if it's the same case for other cmdlets in the module, but I think it would be a good idea to check the examples in the documentation, to see if there is more obsolete stuff in there.

Cheers, Kevin!

**Comment by bateskevin** [comment]
Hey, I just saw that the parameter was probably renamed to 'FolderPath' instead of 'Path', I ceated a PR to fix it in the docs --> #189

**Comment by Tiberriver256** [comment]
🎉🎉🎉

Thank you!
