### ISSUE TITLE
Stoping and Starting on the same port throws prefix error

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/Polaris#19]
Polaris receives the following error when starting after stopping on a particular port in the same PowerShell session. In this example, it was the default 8080 port.

```powershell
PS C:\Users\tyleonha\Polaris\example> $app = Start-Polaris
PS C:\Users\tyleonha\Polaris\example> Stop-Polaris
Server Stopped.
PS C:\Users\tyleonha\Polaris\example> Start-Polaris
Exception calling "Start" with "3" argument(s): "Failed to listen on prefix 'http://localhost:8080/' because it conflicts with an existing
registration on the machine."
At C:\Users\tyleonha\Polaris\Polaris.psm1:115 char:5
+     $global:Polaris.Start($Port, $MinRunspaces, $MaxRunspaces);
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : HttpListenerException

```

**Comment by mikeTWC1984** [comment]
At this moment looks like after Stop/Start there is no error, but server is down anyway. So need to do Stop/Clear/Start. I think it's OK, we can just combine Stop and Clean in one cmdlet (or create some Clone-Polaris cmdlet to kill current instance and create a new one with old routes)

**Comment by harikanth64** [comment]
@TylerLeonhardt I have the same issue. 
I cannot re-run the start-polaris on same port even after clear and stop polaris command.

The above link you provided is not working. 
Can you please guide me to the right solution link.
Thanks.
