### ISSUE TITLE
Question: Authentication 

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/Polaris#190]
Hi @Tiberriver256 / @TylerLeonhardt 

I was scanning your documentation summary for information on 'Authentication'. Unfortunatley, I couldn't find a topic called like that (Perhaps it is simply hidden somwhere else?).

I was trying to figure out if it was possible to handle some authentication stuff (like, this member of this AD group, cannot access to this route).

I think I read something in that direction once, and couldn't find it. Would you mind pointing me in the right direction?

Thanks

#Stéphane

**Comment by Tiberriver256** [comment]
Hey Stephan,

Looks like another gap in the docs. I'll write something up here shortly.

**Comment by apetitjean** [comment]
I'm looking forward reading it too! ;-)

**Comment by Stephanevg** [comment]
Hey @Tiberriver256 , I was planning to this one at work in a few. Is there something I can look into ? (Even a draft would be do the trick)

**Comment by copdips** [comment]
I think we can implement the auth by ourselves by checking the headers in a middleware, and let Polaris as light as possible.

**Comment by TylerLeonhardt** [comment]
You folks may want to look at [Pode](https://github.com/Badgerati/Pode/) which seems a bit further along in this space than Polaris

**Comment by Tiberriver256** [comment]
I started up a short draft here that should be enough to get you started:

https://github.com/Tiberriver256/Polaris/blob/new-authentication-documentation/docs/about_Authentication.md

**Comment by Stephanevg** [comment]
Why you saying that @tylerleonhardt?
Does Polaris doesn't has support for authentication?

**Comment by Badgerati** [comment]
Hey!

As per @Tiberriver256 draft, it's definitely possible to do this in Polaris with Window's AD and have group validation.

Where Pode is bit further ahead, is that Polaris does its authentication via HttpListener, where as Pode is independent and has its own authentication logic using middleware (making it easier to have custom authentication strategies, or when implementing against AWS/Azure Functions).

**Comment by Tiberriver256** [comment]
@Stephanevg - Check out PR #192 and let me know what you think of the docs.

**Comment by Stephanevg** [comment]
Hi @Tiberriver256 Yeah, that looks perfect. It will allow people to get started with it! 
Thanks for updating it :)
('ill close this one once it i merged)
