### ISSUE TITLE
PSReadline again

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/Polaris#194]
Is there any news on PSReadline/*nix issue?

I'm looking for some work around that allows to use Polaris and keep PSReadline. I guess you mention this can be fixed by replacing Register-ObjectEvent whith a while loop. Is it an easy change? If so, can you show any sample code?

Btw, I noticed that this issue disappears if starting Polaris from VSCode Powershell Integrated console

**Comment by Tiberriver256** [comment]
Let's keep the discussion for this in #136 just so any workarounds we discover or are mentioned can be found in the single master thread. I'll repost your question over on that thread and close this one out.
