### ISSUE TITLE
Reroute wiki pages to detailed pages located in /docs

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/Polaris#196]
Just a small side note:

I was navigating in the wiki [here](https://github.com/PowerShell/Polaris/wiki) and I noticed it shows just some 'obvious' examples which don't really help much.

I noticed that a way more detailed help is located here -> https://github.com/PowerShell/Polaris/tree/master/docs

It would make sense to point these wiki articles to these pages as it would be way more helpfull for the end users of this module

**Comment by Tiberriver256** [comment]
Another thing along those lines. Could we change the URL at the top to point to the documentation site instead of the PowerShell gallery @TylerLeonhardt?

https://powershell.github.io/Polaris

**Comment by TylerLeonhardt** [comment]
Added the reference to the docs site on both the wiki and the top of the repo :)
