### ISSUE TITLE
Support query parameters

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/Polaris#24]
They're absolutely necessary.

localhost:8080/hello?name=Tyler

There's a bug to track the investigation of ASP.NET Routing in https://github.com/PowerShell/Polaris/issues/13

but potentially in the meantime we can add on to the additional routing logic to support query parameters.

Should be simple:
1. get the query parameters from the url
2. put them in the PolarisRequest object that gets sent down to the executing PowerShell

**Comment by vors** [comment]
wow, surprised that this is not supported yet :(

**Comment by tylerl0706** [comment]
@vors I've got this working locally. Let me write a few tests and I'll get it out the door 👍

**Comment by tylerl0706** [comment]
Fixed in https://github.com/PowerShell/Polaris/pull/36

**Comment by vors** [comment]
woo, awesome!
