### ISSUE TITLE
Consider support for pluggable authentication

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/Polaris#25]
Hiyo!

This is outside my wheelhouse, but it would be quite valuable to have some sort of authentication, preferably pluggable so that folks could implement different mechanisms.  Apologies if this is already included and I missed it

Cheers!

**Comment by tylerl0706** [comment]
This would fall under https://github.com/PowerShell/Polaris/issues/15 I believe. I'll edit that issue to mention pluggable auth. Thanks!
