### ISSUE TITLE
DotNet SDK Requirement

### ISSUE THREAD

**Issue by Draith6** [PowerShell/Polaris#26]
On a new Win10 Enterprise (1607), using PowerShell 6 beta 8, the default dotnet SDK that is being used errors out when you try to do a 'dotnet restore' or 'dotnet build':
C:\Program Files\dotnet\sdk\1.1.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(126,5): error : The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0. [C:\PowerShell\Modules\Polaris\PolarisCore\Polaris.csproj]

Did I miss a requirement, or should it be listed in the "Getting Started" guide to use a higher level SDK?

**Comment by tylerl0706** [comment]
Hey sorry about that. The requirement would be dotnet sdk 2.0. Let me go ahead and update the readme with that.

Thanks!

**Comment by tylerl0706** [comment]
Addressed in https://github.com/PowerShell/Polaris/pull/30
