### ISSUE TITLE
Why is $Polaris a global variable? 

### ISSUE THREAD

**Issue by oising** [PowerShell/Polaris#34]
It seems it should be left as a module scoped variable.

**Comment by tylerl0706** [comment]
I've addressed the other issue so at least we're no longer leaking a runspace pool - however, this should be a module scoped variable. Right now there are a few tests that rely on that globally scoped variable so this change is a little bit more involved than "find and replace"

That said, it's relatively straight forward. Either a Get-Polaris cmdlet can be added or the tests can hold on the the Polaris variable returned by Start-Polaris

**Comment by chriskuech** [comment]
I just submitted a pr for this issue

**Comment by oising** [comment]
@tylerl0706 Just fyi, if you want to run code in the scope of a module, it's as easy as:

```
import-module mymodule
$m = get-module mymodule
& $m { ... tests ... }
```

or you could pull it out like this:

```
ipmo mymodule
$m = get-module mymodule
$ref = & $m { $polaris }
```

So it's probably easier than you think to replace that global variable.

**Comment by tylerl0706** [comment]
@chriskuech fixed this I believe!
