### ISSUE TITLE
Verify or Support Functionality on Windows IoT Core

### ISSUE THREAD

**Issue by johnnygtech** [PowerShell/Polaris#38]
One major use case I personally see is as a minimalistic way to give Windows IoT Core a PowerShell based alternative to Node.js for web server.

I have not yet had a chance to test Polaris on IoT Core, I will add feedback when I do.

**Comment by tylerl0706** [comment]
I would love to see this and was actually thinking about this today!

In theory, this should work anywhere where PowerShell Core 6 works.

**Comment by johnnygtech** [comment]
I am working on building an ARM version to test on my pi.  I would like to get it done this weekend and report back my findings (I am teaching myself how to build core solutions in the process so its a slow effort)

**Comment by tylerl0706** [comment]
Let me know if I can help in any way!

**Comment by johnnygtech** [comment]
Thinking we table this one in favor of the native powershell issue then come back and verify this works!
