### ISSUE TITLE
Is there support for POSTing data

### ISSUE THREAD

**Issue by affieuk** [PowerShell/Polaris#44]
I've gone through the wiki, can't find examples of post a $body variable, maybe json with convertTo / convertFrom?

Something like
```
New-WebRoute -Path "/" -Method "POST" -ScriptBlock {
    New-Item -Path $body.Path -ItemType Directory
    $response.Send($(Get-Item -Path $body.Path));
}
Start-Polaris -Port 80

###
$body = @{'Path'='C:\Test'}
Invoke-WebRequest -Method Post -Uri http://localhost -Body $body
```

**Comment by tylerl0706** [comment]
Hey thanks for this - I'm actually working on this right now. Expect something by the end of the week :)

**Comment by vors** [comment]
Thank you for fixing #24 
I just realized that Body support (this issue) would be much more useful :)

**Comment by tylerl0706** [comment]
Coming soon @vors :) https://github.com/PowerShell/Polaris/pull/49

**Comment by tylerl0706** [comment]
All merged in! Take a look at https://github.com/PowerShell/Polaris/pull/49 for docs and the wiki
