### ISSUE TITLE
Start-Polaris when there are no routes registered calls some mandatory parameters

### ISSUE THREAD

**Issue by vors** [PowerShell/Polaris#51]
Start polaris without registering any routes.
It runs into a confusing mandatory parameters supply prompt

```
PS /Users/vors/dev/polaris> import-module ./Polaris.psd1                                                             
PS /Users/vors/dev/polaris> Start-Polaris -Verbose                                                                   

cmdlet ThrowError at command pipeline position 1
Supply values for the following parameters:
errorId: 213
errorCategory: 1
```

**Comment by tylerl0706** [comment]
Thanks for this! It's because of this call:
https://github.com/PowerShell/Polaris/blob/master/Polaris.psm1#L150

Should probably get rid of that ThrowError... it's not needed because you can add routes after you've started the server.
