### ISSUE TITLE
Add Cmdlet prefixes 

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/Polaris#76]
It's best practice to change:

`Get-WebRoute`

To

`Get-PolarisWebRoute`

That prefix helps user know what module the cmdlet comes from.

**Comment by doug-reimer** [comment]
I'd like to help out with this one.  I'm a "first issue" contributor, so let me know if you need me to make any changes, or if I have done things horribly wrong!

**Comment by tylerl0706** [comment]
@doug-reimer fixed this 😃
