### ISSUE TITLE
Query Parameters Documentation Incorrect

### ISSUE THREAD

**Issue by doug-reimer** [PowerShell/Polaris#79]
I think the documentation for query parameters needs to be updated to something like:

`$response.QueryParameters` changed to `$response.Query`

`New-WebRoute -Path "/hellome" -Method "GET" -ScriptBlock {
    if ($request.Query['name']) {
        $response.Send('Hello ' + $request.Query['name']);
    } else {
        $response.Send('Hello World');
    }
}`

**Comment by tylerl0706** [comment]
Thanks for this! It's fixed now. I should really make the docs automated 🤔
