### ISSUE TITLE
Use `-UseBasicParsing` in all `Invoke-WebRequest` calls so that IE is not a dependency

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/Polaris#90]
For every `Invoke-WebRequest` in our tests, we need to add `-UseBasicParsing`. Without it, PowerShell on Windows will use IE. We don't want that to happen because we don't need complex parsing of the response body.

**Comment by tylerl0706** [comment]
Thanks to @BladeFireLight for pointing this out!

**Comment by BladeFireLight** [comment]
If think that is the default in v6, but it kills the validations on server core.

**Comment by tylerl0706** [comment]
Yeah there is no `-UseBasicParsing` in v6 so we'll have to check for that.

**Comment by tylerl0706** [comment]
I just found out that v6 has `-UseBasicParsing` it just doesn't do anything because basic parsing is the default. We'll be able to simply add that flag and it should work everywhere.

**Comment by tylerl0706** [comment]
Fixed in #94 😄
