### ISSUE TITLE
Investigate other implementations of Polaris

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/Polaris#93]
When working on the [Azure IoT SDK](https://github.com/tylerl0706/azure-iot-sdk-powershell/) Direct Methods, I got some great feedback regarding script blocks and scope.

Rather than passing in arbitrary script blocks, we could pass in a module that has a function we want to run for a given route.

This way, the module contains the scope of the executing route.

We should enable this for Polaris.

**Comment by tylerl0706** [comment]
Another investigation is the by using Register-ObjectEvent and a background thread in order to handle messages.

Here's a message I wrote from #81:

I prototyped a "full" PowerShell version of Polaris. It doesn't do EVERYTHING Polaris can, but the core of Polaris has been moved over.

There's still a single Add-Type... but at least there's no building required. It even leverages Register-ObjectEvent so no more Runspace management 😄

Here's what I've got so far:

```powershell
Add-Type -TypeDefinition @'
using System;
using System.Net;
using System.Threading;
using System.Threading.Tasks;

namespace Polaris
{
    public class PolarisCore
    {
        public delegate void EventRaised(HttpListenerContext context);
        public event EventRaised myEvent;

        private async Task ListenerLoop(int Port)
        {
            var web = new HttpListener();
            web.Prefixes.Add($"http://localhost:{Port}/");
            Console.WriteLine("Listening..");
            web.Start();
            while (true)
            {
                var context = await web.GetContextAsync();
                myEvent(context);
            }
        }

        public void Start(int Port = 8080)
        {
            Thread listenerThread = new Thread(async () => { await ListenerLoop(Port); });
            listenerThread.Start();
        }
    }
}
'@

$ROUTES = [hashtable]@{}

function Register-PolarisRoute {
    param(
        [string]
        $Path,
        [string]
        $Method,
        [scriptblock]
        $ScriptBlock
    )

    if (-not $ROUTES[$Method]){
        $ROUTES[$Method] = [hashtable]@{}
    }
    $ROUTES[$Method][$Path.Trim("/")] = $ScriptBlock
    
}

function Start-Polaris {  
    param(
        [int]
        $Port = 8080
    )
    $polarisCore = [Polaris.PolarisCore]::new()
    $polarisCore.Start($Port)

    Register-ObjectEvent -InputObject $polarisCore -EventName myEvent -Action {
        $response = $Args[0].Response

        $Path = $Args[0].Request.RawUrl.Trim("/")
        $Method = $Args[0].Request.HttpMethod

        Write-Host "$Method $Path"

        if ($ROUTES[$Method] -and $ROUTES[$Method][$Path]) {
            $responseString = $ROUTES[$Method][$Path].Invoke()[0]
        }
        else {
            $responseString = "Not Found"
        }
        Write-Host $responseString
        $buffer = [System.Text.Encoding]::UTF8.GetBytes($responseString)
        $response.ContentLength64 = $buffer.Length
        $output = $response.OutputStream
        $output.Write($buffer, 0, $buffer.Length)
        $output.Close()
    }
}
```

This prototype lets you do:

```powershell
Register-PolarisRoute -Path /hello -Method Get -ScriptBlock {
    return "wow"
}

Start-Polaris
```

Not only that, but a "new feature" of using the active runspace means scoping isn't as painful!
```powershell
$hey = "hey"
Register-PolarisRoute -Path /hello -Method Get -ScriptBlock {
    return "wow $hey"
}

Start-Polaris -Port 8082
```
Works as you expect!

I'm really liking this model over the previous implementation. Would love some feedback :)

(NOTE: I know that that snippet of code doesn't do EVERYTHING that the current Polaris can, but it lays a foundation that can be built on top of to get to feature parity)

**Comment by Tiberriver256** [comment]
Alright, so here's my thoughts. The Register-ObjectEvent works great but would be a pretty big shift I think in that you couldn't call the API from the same instance of PowerShell. Just give Invoke-RestMethod a try and everything locks up (times out actually) because the listener is async but the action is synchronous.

It's not necessarily a game stopper though. It would just mean we would have to separate our Pester tests into unit that can be executed on the same thread and end to end tests that would need to have Polaris executed in a background job or something. I think this pattern of testing is pretty common too so it wouldn't be a big jump for most.

Also, a note, I have done this same thing with a PowerShell runspace if we wanted to keep it pure PowerShell. It would just be the listener running in the runspace so it would be much simpler.

**Comment by tylerl0706** [comment]
Awesome investigation @Tiberriver256! Thanks for that. You bring up some awesome point - here's my initial thought. Personally, I believe Register-ObjectEvent  is the best future of Polaris - and the issue you bring up is not a game stopper.

Why? Here are my reasons:

#### It fixes the weird Scope problem

The thing that bothers me the most about Polaris' current implementation is the fact that `$hey` in the script block would be null in the following example:
```powershell
$hey = "hey"
Register-PolarisRoute -Path /hello -Method Get -ScriptBlock {
    return "wow $hey"
}

Start-Polaris -Port 8082
```

I wrote Polaris with [Expressjs](https://expressjs.com/en/guide/routing.html) as an example of how I wanted it to look and the fact that scope is totally lost is really sad.

#### I really don't like managing runspaces

I feel like debugging code that runs in a totally other runspace is incredibly frustrating to debug. I kinda got around this in the last version of Polaris by collecting the errors and sending them back... but that shouldn't really be the only source of logging.

Oh yeah, and Write-Host was a pain inside of a runspace... 

moral of the story, I don't care too much for runspaces. I appreciate them, but don't think they meet every need.

#### Register-ObjectEvent seems more PowerShell-y to me then the module approach

I mentioned that I don't like the scope issue... but the other solution to that problem is the module approach where you have a psm1 that has some functions in it that can be run for each of the different routes. 

I like the thought of this idea, because it fixes the scoping issue and you can refer to your psm1 as your route definition, but I think it's a little too complicated compared to the Register-ObjectEvent solution which lets you just have a `.ps1`.

#### The game stopper can be avoided using a PowerShell job

As you hinted at, using PowerShell's built in Job feature, we could quite easily run the Polaris server on a background runspace with: 

```powershell
Start-Job path/to/my/app.ps1
```

Then we should be able to use the web cmdlets as we expect. I haven't tested this but I'm pretty sure.

**Comment by Tiberriver256** [comment]
Sounds good to me. It should make the code and writing code for the server soooo much simpler too.

**Comment by tylerl0706** [comment]
we did it :)

**Comment by tylerl0706** [comment]
Well @Tiberriver256 did it 😎

**Comment by Tiberriver256** [comment]
Hey don't discount the value of your excellent code reviews!

**Comment by PingMudit** [comment]
> Another investigation is the by using Register-ObjectEvent and a background thread in order to handle messages.
> 
> Here's a message I wrote from #81:
> 
> I prototyped a "full" PowerShell version of Polaris. It doesn't do EVERYTHING Polaris can, but the core of Polaris has been moved over.
> 
> There's still a single Add-Type... but at least there's no building required. It even leverages Register-ObjectEvent so no more Runspace management 😄
> 
> Here's what I've got so far:
> 
> ```powershell
> Add-Type -TypeDefinition @'
> using System;
> using System.Net;
> using System.Threading;
> using System.Threading.Tasks;
> 
> namespace Polaris
> {
>     public class PolarisCore
>     {
>         public delegate void EventRaised(HttpListenerContext context);
>         public event EventRaised myEvent;
> 
>         private async Task ListenerLoop(int Port)
>         {
>             var web = new HttpListener();
>             web.Prefixes.Add($"http://localhost:{Port}/");
>             Console.WriteLine("Listening..");
>             web.Start();
>             while (true)
>             {
>                 var context = await web.GetContextAsync();
>                 myEvent(context);
>             }
>         }
> 
>         public void Start(int Port = 8080)
>         {
>             Thread listenerThread = new Thread(async () => { await ListenerLoop(Port); });
>             listenerThread.Start();
>         }
>     }
> }
> '@
> 
> $ROUTES = [hashtable]@{}
> 
> function Register-PolarisRoute {
>     param(
>         [string]
>         $Path,
>         [string]
>         $Method,
>         [scriptblock]
>         $ScriptBlock
>     )
> 
>     if (-not $ROUTES[$Method]){
>         $ROUTES[$Method] = [hashtable]@{}
>     }
>     $ROUTES[$Method][$Path.Trim("/")] = $ScriptBlock
>     
> }
> 
> function Start-Polaris {  
>     param(
>         [int]
>         $Port = 8080
>     )
>     $polarisCore = [Polaris.PolarisCore]::new()
>     $polarisCore.Start($Port)
> 
>     Register-ObjectEvent -InputObject $polarisCore -EventName myEvent -Action {
>         $response = $Args[0].Response
> 
>         $Path = $Args[0].Request.RawUrl.Trim("/")
>         $Method = $Args[0].Request.HttpMethod
> 
>         Write-Host "$Method $Path"
> 
>         if ($ROUTES[$Method] -and $ROUTES[$Method][$Path]) {
>             $responseString = $ROUTES[$Method][$Path].Invoke()[0]
>         }
>         else {
>             $responseString = "Not Found"
>         }
>         Write-Host $responseString
>         $buffer = [System.Text.Encoding]::UTF8.GetBytes($responseString)
>         $response.ContentLength64 = $buffer.Length
>         $output = $response.OutputStream
>         $output.Write($buffer, 0, $buffer.Length)
>         $output.Close()
>     }
> }
> ```
> 
> This prototype lets you do:
> 
> ```powershell
> Register-PolarisRoute -Path /hello -Method Get -ScriptBlock {
>     return "wow"
> }
> 
> Start-Polaris
> ```
> 
> Not only that, but a "new feature" of using the active runspace means scoping isn't as painful!
> 
> ```powershell
> $hey = "hey"
> Register-PolarisRoute -Path /hello -Method Get -ScriptBlock {
>     return "wow $hey"
> }
> 
> Start-Polaris -Port 8082
> ```
> 
> Works as you expect!
> 
> I'm really liking this model over the previous implementation. Would love some feedback :)
> 
> (NOTE: I know that that snippet of code doesn't do EVERYTHING that the current Polaris can, but it lays a foundation that can be built on top of to get to feature parity)

Looks very promising :)
I am trying to run this but getting error as shown here. Could you please help?
![image](https://user-images.githubusercontent.com/51925798/143990519-fafd457f-d80b-417b-9ebc-c5cb00209029.png)
